'use client'

import { useState, useEffect } from 'react'
import { useAuth } from '@/app/providers'
import {
  getDiagnoses,
  deleteDiagnosis,
  createShareableLink,
} from '@/lib/supabase'
import { generatePDFReport, generateShareableLink } from '@/lib/pdf-export'
import Link from 'next/link'
import { ArrowLeft, Download, Share2, Trash2, Copy } from 'lucide-react'

export default function HealthHistory() {
  const { user } = useAuth()
  const isDemoUser = user?.email === 'demo@medai.health'
  const isDoctor = user?.role === 'doctor' || user?.email?.endsWith('@medai.health')

  const [diagnoses, setDiagnoses] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [shareTokens, setShareTokens] = useState<Record<string, string>>({})
  const [copiedIds, setCopiedIds] = useState<Record<string, boolean>>({})
  const [expandedId, setExpandedId] = useState<string | null>(null)

  useEffect(() => {
    if (!user) return

    const fetchDiagnoses = async () => {
      try {
        const { data } = await getDiagnoses(user.id)
        setDiagnoses(data || [])
      } catch (error) {
        console.error('Error fetching diagnoses:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchDiagnoses()
  }, [user])

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure?')) return

    try {
      await deleteDiagnosis(id)
      setDiagnoses(diagnoses.filter((d) => d.id !== id))
    } catch (error) {
      console.error('Error deleting diagnosis:', error)
    }
  }

  const handleShare = async (
    id: string,
    accessMode: 'public' | 'doctor' = 'public'
  ) => {
    try {
      const { data, error } = await createShareableLink(id, accessMode)
      if (error) {
        console.error('Error creating shareable link:', error)
        return
      }

      const token = (data as any)?.[0]?.share_token
      if (token) {
        setShareTokens((prev) => ({ ...prev, [id]: token }))
      }
    } catch (error) {
      console.error('Error creating shareable link:', error)
    }
  }

  const handleCopyLink = (id: string) => {
    const token = shareTokens[id]
    if (!token) return

    const link = generateShareableLink(token)
    navigator.clipboard.writeText(link)
    setCopiedIds((prev) => ({ ...prev, [id]: true }))
    setTimeout(() => setCopiedIds((prev) => ({ ...prev, [id]: false })), 2000)
  }

  const handleExportPDF = async (id: string) => {
    try {
      const diagnosis = diagnoses.find((d) => d.id === id)
      if (!diagnosis) return

      const reportHTML = `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h1>MedAI Health Report</h1>
          <h2>Diagnosis Report</h2>
          <p><strong>Date:</strong> ${new Date(diagnosis.created_at).toLocaleDateString()}</p>
          <p><strong>Symptoms:</strong> ${diagnosis.symptoms}</p>
          
          <h3>Differential Diagnosis</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background-color: #f0f0f0;">
                <th style="border: 1px solid #ddd; padding: 8px;">Condition</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Confidence</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Severity</th>
              </tr>
            </thead>
            <tbody>
              ${diagnosis.diagnosis_data?.differential_diagnosis
                ?.map(
                  (item: any) => `
                <tr>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.condition}</td>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.confidence}%</td>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.severity}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>
          
          ${
            diagnosis.diagnosis_data?.red_flags &&
            diagnosis.diagnosis_data?.red_flags.length > 0
              ? `
            <h3>Red Flags ⚠️</h3>
            <ul>
              ${diagnosis.diagnosis_data?.red_flags
                .map((flag: string) => `<li>${flag}</li>`)
                .join('')}
            </ul>
          `
              : ''
          }
          
          <p style="margin-top: 20px; font-size: 12px; color: #666;">
            This report is generated by MedAI and should not replace professional medical advice.
          </p>
        </div>
      `

      const tempDiv = document.createElement('div')
      tempDiv.id = `report-${id}`
      tempDiv.innerHTML = reportHTML
      document.body.appendChild(tempDiv)

      await generatePDFReport(`report-${id}`, `diagnosis-${id}.pdf`)
      document.body.removeChild(tempDiv)
    } catch (error) {
      console.error('Error exporting PDF:', error)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-healthcare-50 to-healthcare-100 flex items-center justify-center">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-healthcare-600"></div>
          <p className="mt-4 text-healthcare-600">Loading...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-healthcare-50 to-healthcare-100">
      <nav className="bg-white shadow-md">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <Link
            href="/dashboard"
            className="flex items-center gap-2 text-healthcare-600 hover:underline"
          >
            <ArrowLeft size={20} />
            Back to Dashboard
          </Link>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-gray-800 mb-2">
          📋 Health History
        </h1>
        <p className="text-gray-600 mb-8">
          View, export, and share your past diagnoses
        </p>

        {isDemoUser && (
          <div className="mb-6 p-4 border-l-4 border-blue-500 bg-blue-50 text-blue-700 rounded-lg">
            Demo mode active: your data is reset periodically. The core workflow is real-time but this account is mock data for quick testing.
          </div>
        )}

        {isDoctor && (
          <div className="mb-6 p-4 border-l-4 border-green-500 bg-green-50 text-green-700 rounded-lg">
            Doctor access: share links can be marked doctor-only. Use this to keep patient data HIPAA-like private.
          </div>
        )}

        {diagnoses.length === 0 ? (
          <div className="card text-center py-12">
            <p className="text-gray-600 text-lg mb-4">
              No diagnoses yet. Start by analyzing your symptoms!
            </p>
            <Link href="/analysis" className="btn-primary">
              Go to Symptom Analysis
            </Link>
          </div>
        ) : (
          <div className="space-y-4">
            {diagnoses.map((diagnosis) => (
              <div
                key={diagnosis.id}
                className="card hover:shadow-lg transition-shadow"
              >
                <div
                  className="cursor-pointer flex justify-between items-start"
                  onClick={() =>
                    setExpandedId(
                      expandedId === diagnosis.id ? null : diagnosis.id
                    )
                  }
                >
                  <div className="flex-1">
                    <p className="text-sm text-gray-500">
                      {new Date(diagnosis.created_at).toLocaleString()}
                    </p>
                    <p className="font-semibold text-gray-800 mt-1">
                      {diagnosis.symptoms.substring(0, 100)}
                      {diagnosis.symptoms.length > 100 ? '...' : ''}
                    </p>

                    {diagnosis.diagnosis_data?.differential_diagnosis &&
                      diagnosis.diagnosis_data.differential_diagnosis.length >
                        0 && (
                        <div className="flex gap-2 mt-2">
                          {diagnosis.diagnosis_data.differential_diagnosis
                            .slice(0, 3)
                            .map((item: any, idx: number) => (
                              <span
                                key={idx}
                                className="text-xs bg-healthcare-100 text-healthcare-700 px-2 py-1 rounded"
                              >
                                {item.condition} ({item.confidence}%)
                              </span>
                            ))}
                        </div>
                      )}
                  </div>

                  <div className="flex gap-2 ml-4">
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleExportPDF(diagnosis.id)
                      }}
                      className="p-2 bg-blue-100 text-blue-600 rounded-lg hover:bg-blue-200 transition-colors"
                      title="Export as PDF"
                    >
                      <Download size={18} />
                    </button>

                    <div className="relative">
                      <select
                        value={diagnosis.access || 'public'}
                        onChange={(e) => {
                          e.stopPropagation()
                          const access = e.target.value as 'public' | 'doctor'
                          handleShare(diagnosis.id, access)
                        }}
                        className="p-2 rounded-lg border border-gray-300 bg-white text-xs"
                        title="Share access mode"
                      >
                        <option value="public">Public</option>
                        <option value="doctor">Doctor-only</option>
                      </select>
                    </div>

                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleShare(diagnosis.id)
                      }}
                      className="p-2 bg-green-100 text-green-600 rounded-lg hover:bg-green-200 transition-colors"
                      title="Create shareable link"
                    >
                      <Share2 size={18} />
                    </button>

                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleDelete(diagnosis.id)
                      }}
                      className="p-2 bg-red-100 text-red-600 rounded-lg hover:bg-red-200 transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                </div>

                {/* Expanded Details */}
                {expandedId === diagnosis.id && (
                  <div className="mt-6 pt-6 border-t border-gray-200 space-y-4">
                    <div>
                      <h4 className="font-bold text-gray-800 mb-2">
                        Full Symptoms
                      </h4>
                      <p className="text-gray-600">{diagnosis.symptoms}</p>
                    </div>

                    {diagnosis.diagnosis_data?.differential_diagnosis && (
                      <div>
                        <h4 className="font-bold text-gray-800 mb-2">
                          Differential Diagnosis
                        </h4>
                        <div className="space-y-2">
                          {diagnosis.diagnosis_data.differential_diagnosis.map(
                            (item: any, idx: number) => (
                              <div
                                key={idx}
                                className="p-3 bg-healthcare-50 border border-healthcare-200 rounded"
                              >
                                <div className="flex justify-between">
                                  <span className="font-medium">
                                    {item.condition}
                                  </span>
                                  <span className="text-healthcare-600 font-bold">
                                    {item.confidence}%
                                  </span>
                                </div>
                                <p className="text-sm text-gray-600 mt-1">
                                  Severity: {item.severity}
                                </p>
                              </div>
                            )
                          )}
                        </div>
                      </div>
                    )}

                    {/* Share Link Section */}
                    {shareTokens[diagnosis.id] && (
                      <div className="bg-green-50 p-4 rounded-lg border border-green-200">
                        <h4 className="font-bold text-green-700 mb-3">
                          ✅ Shareable Link Created
                        </h4>
                        <div className="flex flex-col sm:flex-row gap-2">
                          <input
                            type="text"
                            readOnly
                            value={generateShareableLink(shareTokens[diagnosis.id])}
                            className="flex-1 px-3 py-2 border border-green-300 rounded-lg bg-white text-sm"
                          />
                          <button
                            onClick={() => handleCopyLink(diagnosis.id)}
                            className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2"
                          >
                            <Copy size={16} />
                            {copiedIds[diagnosis.id] ? 'Copied!' : 'Copy'}
                          </button>
                        </div>
                        <p className="text-xs text-green-600 mt-2">
                          Share this link with your doctor or patient.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
