import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export async function generatePDFReport(
  elementId: string,
  fileName: string
): Promise<void> {
  try {
    const element = document.getElementById(elementId)
    if (!element) throw new Error('Element not found')

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p', 'mm', 'a4')

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const imgWidth = pageWidth - 20
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    let heightLeft = imgHeight
    let position = 10

    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
    heightLeft -= pageHeight - 20

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
      heightLeft -= pageHeight - 20
    }

    pdf.save(fileName)
  } catch (error) {
    console.error('Error generating PDF:', error)
    throw error
  }
}

export function generateShareableLink(diagnosisId: string, token: string): string {
  return `${process.env.NEXT_PUBLIC_APP_URL}/share/${token}`
}

export async function createHealthReportHTML(diagnosis: any): Promise<string> {
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h1>MedAI Health Report</h1>
      <h2>Diagnosis Report</h2>
      <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
      <p><strong>Symptoms:</strong> ${diagnosis.symptoms}</p>
      
      <h3>Differential Diagnosis</h3>
      <table style="width: 100%; border-collapse: collapse;">
        <thead>
          <tr style="background-color: #f0f0f0;">
            <th style="border: 1px solid #ddd; padding: 8px;">Condition</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Confidence</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Severity</th>
          </tr>
        </thead>
        <tbody>
          ${diagnosis.differential_diagnosis
            .map(
              (item: any) => `
            <tr>
              <td style="border: 1px solid #ddd; padding: 8px;">${item.condition}</td>
              <td style="border: 1px solid #ddd; padding: 8px;">${item.confidence}%</td>
              <td style="border: 1px solid #ddd; padding: 8px;">${item.severity}</td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>
      
      ${
        diagnosis.red_flags && diagnosis.red_flags.length > 0
          ? `
        <h3>Red Flags ⚠️</h3>
        <ul>
          ${diagnosis.red_flags.map((flag: string) => `<li>${flag}</li>`).join('')}
        </ul>
      `
          : ''
      }
      
      ${
        diagnosis.next_steps && diagnosis.next_steps.length > 0
          ? `
        <h3>Recommended Next Steps</h3>
        <ol>
          ${diagnosis.next_steps
            .map((step: string) => `<li>${step}</li>`)
            .join('')}
        </ol>
      `
          : ''
      }
      
      <p style="margin-top: 20px; font-size: 12px; color: #666;">
        This report is generated by MedAI and should not replace professional medical advice.
      </p>
    </div>
  `
  return html
}
