'use client'

import { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import { getSharedReport } from '@/lib/supabase'
import { generatePDFReport } from '@/lib/pdf-export'
import { Download, AlertCircle } from 'lucide-react'

export default function SharedReport() {
  const params = useParams()
  const token = params.token as string
  const [diagnosis, setDiagnosis] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const report = await getSharedReport(token)
        if (report.error) {
          setError(report.error)
        } else {
          setDiagnosis(report.diagnosis)
        }
      } catch (err: any) {
        setError(err.message || 'Error loading report')
      } finally {
        setLoading(false)
      }
    }

    if (token) {
      fetchReport()
    }
  }, [token])

  const handleExportPDF = async () => {
    if (!diagnosis) return
    try {
      const reportHTML = `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h1>MedAI Health Report</h1>
          <h2>Diagnosis Report</h2>
          <p><strong>Date:</strong> ${new Date(diagnosis.created_at).toLocaleDateString()}</p>
          <p><strong>Symptoms:</strong> ${diagnosis.symptoms}</p>
          
          <h3>Differential Diagnosis</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background-color: #f0f0f0;">
                <th style="border: 1px solid #ddd; padding: 8px;">Condition</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Confidence</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Severity</th>
              </tr>
            </thead>
            <tbody>
              ${diagnosis.diagnosis_data?.differential_diagnosis
                ?.map(
                  (item: any) => `
                <tr>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.condition}</td>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.confidence}%</td>
                  <td style="border: 1px solid #ddd; padding: 8px;">${item.severity}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>
          
          ${
            diagnosis.diagnosis_data?.red_flags &&
            diagnosis.diagnosis_data?.red_flags.length > 0
              ? `
            <h3>Red Flags ⚠️</h3>
            <ul>
              ${diagnosis.diagnosis_data?.red_flags
                .map((flag: string) => `<li>${flag}</li>`)
                .join('')}
            </ul>
          `
              : ''
          }
          
          <p style="margin-top: 20px; font-size: 12px; color: #666;">
            This report is generated by MedAI and should not replace professional medical advice.
          </p>
        </div>
      `

      const tempDiv = document.createElement('div')
      tempDiv.id = 'shared-report'
      tempDiv.innerHTML = reportHTML
      document.body.appendChild(tempDiv)

      await generatePDFReport('shared-report', 'medai-health-report.pdf')
      document.body.removeChild(tempDiv)
    } catch (error) {
      console.error('Error exporting PDF:', error)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-healthcare-50 to-healthcare-100 flex items-center justify-center">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-healthcare-600"></div>
          <p className="mt-4 text-healthcare-600">Loading report...</p>
        </div>
      </div>
    )
  }

  if (error || !diagnosis) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-healthcare-50 to-healthcare-100 flex items-center justify-center p-4">
        <div className="max-w-md w-full card border-l-4 border-red-600">
          <div className="flex gap-3">
            <AlertCircle className="text-red-600 flex-shrink-0" size={24} />
            <div>
              <h1 className="text-2xl font-bold text-red-600 mb-2">Error</h1>
              <p className="text-gray-700">{error}</p>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-healthcare-50 to-healthcare-100">
      <nav className="bg-white shadow-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-healthcare-600">MedAI</h1>
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-2 btn-primary"
          >
            <Download size={20} />
            Export PDF
          </button>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-4 py-12">
        <div id="report-content" className="card space-y-6">
          <div className="border-b pb-4">
            <h1 className="text-4xl font-bold text-healthcare-600 mb-2">
              🏥 MedAI Health Report
            </h1>
            <p className="text-gray-600">
              Generated on{' '}
              {new Date(diagnosis.created_at).toLocaleString()}
            </p>
          </div>

          {/* Symptoms Section */}
          <div>
            <h2 className="text-2xl font-bold text-gray-800 mb-3">
              Reported Symptoms
            </h2>
            <p className="text-gray-700 bg-gray-50 p-4 rounded-lg">
              {diagnosis.symptoms}
            </p>
          </div>

          {/* Differential Diagnosis */}
          {diagnosis.diagnosis_data?.differential_diagnosis && (
            <div>
              <h2 className="text-2xl font-bold text-gray-800 mb-3">
                Differential Diagnosis
              </h2>
              <div className="overflow-x-auto">
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="bg-healthcare-100 border">
                      <th className="px-4 py-3 text-left font-bold border">
                        Condition
                      </th>
                      <th className="px-4 py-3 text-center font-bold border">
                        Confidence
                      </th>
                      <th className="px-4 py-3 text-left font-bold border">
                        Severity
                      </th>
                      {diagnosis.diagnosis_data?.differential_diagnosis[0]
                        ?.icd_code && (
                        <th className="px-4 py-3 text-left font-bold border">
                          ICD-10 Code
                        </th>
                      )}
                    </tr>
                  </thead>
                  <tbody>
                    {diagnosis.diagnosis_data.differential_diagnosis.map(
                      (item: any, idx: number) => (
                        <tr key={idx} className="border">
                          <td className="px-4 py-3 border">{item.condition}</td>
                          <td className="px-4 py-3 text-center border">
                            <span className="bg-healthcare-600 text-white px-3 py-1 rounded-full text-sm font-bold">
                              {item.confidence}%
                            </span>
                          </td>
                          <td className="px-4 py-3 border">
                            <span
                              className={`px-3 py-1 rounded-full text-sm font-bold ${
                                item.severity?.toLowerCase() === 'severe'
                                  ? 'bg-red-100 text-red-700'
                                  : item.severity?.toLowerCase() === 'moderate'
                                    ? 'bg-yellow-100 text-yellow-700'
                                    : 'bg-green-100 text-green-700'
                              }`}
                            >
                              {item.severity}
                            </span>
                          </td>
                          {item.icd_code && (
                            <td className="px-4 py-3 border text-gray-600 text-sm">
                              {item.icd_code}
                            </td>
                          )}
                        </tr>
                      )
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Red Flags */}
          {diagnosis.diagnosis_data?.red_flags &&
            diagnosis.diagnosis_data.red_flags.length > 0 && (
              <div className="bg-red-50 border-l-4 border-red-600 p-4 rounded">
                <h3 className="text-lg font-bold text-red-700 mb-3">
                  ⚠️ Red Flags
                </h3>
                <ul className="space-y-2 text-red-600">
                  {diagnosis.diagnosis_data.red_flags.map(
                    (flag: string, idx: number) => (
                      <li key={idx} className="flex gap-2">
                        <span>•</span>
                        <span>{flag}</span>
                      </li>
                    )
                  )}
                </ul>
              </div>
            )}

          {/* Next Steps */}
          {diagnosis.diagnosis_data?.next_steps &&
            diagnosis.diagnosis_data.next_steps.length > 0 && (
              <div className="bg-green-50 border-l-4 border-green-600 p-4 rounded">
                <h3 className="text-lg font-bold text-green-700 mb-3">
                  ✅ Recommended Next Steps
                </h3>
                <ol className="space-y-2 text-green-600 list-decimal list-inside">
                  {diagnosis.diagnosis_data.next_steps.map(
                    (step: string, idx: number) => (
                      <li key={idx}>{step}</li>
                    )
                  )}
                </ol>
              </div>
            )}

          {/* Disclaimer */}
          <div className="bg-blue-50 border-l-4 border-blue-600 p-4 rounded text-sm">
            <p className="text-blue-700 font-bold mb-2">📋 Medical Disclaimer</p>
            <p className="text-blue-600">
              This report is generated by MedAI AI system as an informational
              tool and should NOT be considered a substitute for professional
              medical advice, diagnosis, or treatment. Always consult with a
              qualified healthcare professional before making any medical
              decisions. In case of emergency, please call emergency services
              or visit your nearest hospital.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
